# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BankItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoryBankApp.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('priority', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=999)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoryBankApp.List')),
            ],
        ),
    ]
