# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryBankApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='notes',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='priority',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
