# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryBankApp', '0002_auto_20170304_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='notes',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='priority',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
