# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryBankApp', '0005_auto_20170313_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listitem',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
