# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoryBankApp', '0006_auto_20170316_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('long_text', models.CharField(blank=True, max_length=9999, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bankitem',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memoryBankApp.Bank'),
        ),
    ]
